import React from 'react';

interface SubjectMark {
  subject: string;
  mark: string | number;
}

interface ResultCardProps {
  student: {
    name: string;
    class: string;
    id: string;
    photoUrl?: string;
  };
  result: {
    exam: string;
    subjects: SubjectMark[];
    total: string | number;
    rank?: string | number;
  };
  schoolName: string;
  schoolLogoUrl?: string;
}

const ResultCard: React.FC<ResultCardProps> = ({ student, result, schoolName, schoolLogoUrl }) => {
  return (
    <div
      className="w-[500px] mx-auto bg-white border border-gray-300 rounded-lg shadow-sm p-6 text-gray-900"
      style={{ pageBreakInside: 'avoid' }}
    >
      <div className="flex items-center mb-4">
        {schoolLogoUrl && (
          <img
            src={getAbsoluteUrl(schoolLogoUrl)}
            alt="School Logo"
            className="h-12 w-12 mr-3 rounded-full border"
          />
        )}
        <div>
          <h2 className="text-lg font-bold">{schoolName}</h2>
          <div className="text-sm font-semibold text-gray-700">Result Card</div>
        </div>
      </div>
      <div className="flex items-center mb-3">
        {student.photoUrl && (
          <img
            src={getAbsoluteUrl(student.photoUrl)}
            alt="Student"
            className="h-16 w-16 rounded border mr-4"
          />
        )}
        <div className="text-[10px]">
          <div><span className="font-semibold">Name:</span> {student.name}</div>
          <div><span className="font-semibold">Class:</span> {student.class}</div>
          <div><span className="font-semibold">Student ID:</span> {student.id}</div>
        </div>
      </div>
      <div className="mb-3 text-[10px]">
        <span className="font-semibold">Exam:</span> {result.exam}
      </div>
      <table className="w-full border text-[10px] mb-3">
        <thead>
          <tr className="bg-gray-100">
            <th className="border px-2 py-1">Subject</th>
            <th className="border px-2 py-1">Mark</th>
          </tr>
        </thead>
        <tbody>
          {result.subjects.map((sub, idx) => (
            <tr key={idx}>
              <td className="border px-2 py-1">{sub.subject}</td>
              <td className="border px-2 py-1">{sub.mark}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <div className="flex justify-between text-[10px]">
        <div><span className="font-semibold">Total:</span> {result.total}</div>
        {result.rank && <div><span className="font-semibold">Rank:</span> {result.rank}</div>}
      </div>
      <div className="mt-6 flex justify-between text-[8px] text-gray-500">
        <div>Generated by MySchool Official</div>
        <div>Date: {new Date().toLocaleDateString()}</div>
      </div>
    </div>
  );
};

export default ResultCard; 