import React from 'react';
import { getAbsoluteUrl } from '@/lib/utils';

interface SeatPlanProps {
  students: {
    name: string;
    class: string;
    id: string;
    seat: string;
    photoUrl?: string;
  }[];
  exam: string;
  room: string;
  schoolName: string;
  schoolLogoUrl?: string;
}

const SeatPlan: React.FC<SeatPlanProps> = ({ students, exam, room, schoolName, schoolLogoUrl }) => {
  return (
    <div className="w-[600px] mx-auto grid grid-cols-2 gap-3 p-4">
      {students.map((student, idx) => (
        <div
          key={idx}
          className="border border-gray-300 rounded-lg shadow-sm p-3 h-[280px] flex flex-col justify-between"
          style={{ pageBreakInside: 'avoid' }}
        >
          <div className="flex items-center mb-1">
            {schoolLogoUrl && (
              <img
                src={getAbsoluteUrl(schoolLogoUrl)}
                alt="School Logo"
                className="h-8 w-8 mr-2 rounded-full border"
              />
            )}
            <div>
              <h2 className="text-sm font-bold leading-tight">{schoolName}</h2>
              <div className="text-[10px] font-semibold text-gray-700">Exam Seat Plan</div>
            </div>
          </div>
          <div className="flex items-center mb-1">
            {student.photoUrl && (
              <img
                src={getAbsoluteUrl(student.photoUrl)}
                alt="Student"
                className="h-10 w-10 rounded border mr-2"
              />
            )}
            <div className="text-[10px]">
              <div><span className="font-semibold">Name:</span> {student.name}</div>
              <div><span className="font-semibold">Class:</span> {student.class}</div>
              <div><span className="font-semibold">Student ID:</span> {student.id}</div>
              <div><span className="font-semibold">Seat:</span> {student.seat}</div>
            </div>
          </div>
          <div className="mb-1 text-[10px]">
            <span className="font-semibold">Exam:</span> {exam}
          </div>
          <div className="mb-1 text-[10px]">
            <span className="font-semibold">Room:</span> {room}
          </div>
          <div className="text-[8px] text-gray-500 flex justify-between">
            <div>Generated by MySchool Official</div>
            <div>Date: {new Date().toLocaleDateString()}</div>
          </div>
        </div>
      ))}
    </div>
  );
};

export default SeatPlan; 